// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pathwise.Infrastructure.Persistence;

#nullable disable

namespace Pathwise.Infrastructure.Migrations
{
    [DbContext(typeof(PathwiseDbContext))]
    partial class PathwiseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Pathwise.Infrastructure.Persistence.MatchPayloadEntity", b =>
                {
                    b.Property<string>("MatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FailureHttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RetrievedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RetryAfterUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("MatchId", "Kind");

                    b.ToTable("MatchPayloads", (string)null);
                });

            modelBuilder.Entity("Pathwise.Infrastructure.Persistence.PlayerAccountEntity", b =>
                {
                    b.Property<string>("Puuid")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfiguredGameName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfiguredTagLine")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Regional")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ResolvedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagLine")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Puuid");

                    b.ToTable("PlayerAccounts", (string)null);
                });

            modelBuilder.Entity("Pathwise.Infrastructure.Persistence.StoredMatchEntity", b =>
                {
                    b.Property<string>("MatchId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChampionName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DiscoveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("MetadataErrorAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PlayedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerPuuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("QueueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Regional")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamPosition")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Won")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchId");

                    b.HasIndex("PlayerPuuid", "QueueId", "PlayedAtUtc");

                    b.ToTable("StoredMatches", (string)null);
                });

            modelBuilder.Entity("Pathwise.Infrastructure.Persistence.MatchPayloadEntity", b =>
                {
                    b.HasOne("Pathwise.Infrastructure.Persistence.StoredMatchEntity", "Match")
                        .WithMany("Payloads")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Pathwise.Infrastructure.Persistence.StoredMatchEntity", b =>
                {
                    b.HasOne("Pathwise.Infrastructure.Persistence.PlayerAccountEntity", "Player")
                        .WithMany("Matches")
                        .HasForeignKey("PlayerPuuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Pathwise.Infrastructure.Persistence.PlayerAccountEntity", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Pathwise.Infrastructure.Persistence.StoredMatchEntity", b =>
                {
                    b.Navigation("Payloads");
                });
#pragma warning restore 612, 618
        }
    }
}
